# -*- coding: utf-8 -*-
"""StorJ_Save_Files.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12_UJg1mDDoZta0ddUIs63SAHnNoZALHG
"""

!pip3 install pandas==1.20

!pip3 install s3fs

import os

import numpy as np
import pandas as pd

# loading environment variables
ACCESS_KEY_ID = os.getenv("ACCESS_KEY_ID")
SECRET_ACCESS_KEY = os.getenv("SECRET_ACCESS_KEY")
ENDPOINT_URL = os.getenv("ENDPOINT_URL")

storage_options = {
  'key': ACCESS_KEY_ID,
  'secret': SECRET_ACCESS_KEY,
  'client_kwargs': {
    'endpoint_url': ENDPOINT_URL
  }
}

#Load CSV File of Data into the Google Colab Environment
from google.colab import files
upload = files.upload()

bucket = "mybucket"
key = "BlockFuse_NLP_Data_Input_Train - Sheet1.csv"

# Creating a random dataframe.
df = pd.read_csv("BlockFuse_NLP_Data_Input_Train - Sheet1.csv")

# Saving as CSV
df.to_csv(
  f"s3://{bucket}/{key}",
  index=False,
  storage_options=storage_options)